name: Docker Validation

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate docker-compose
        run: docker compose config

      - name: Build containers
        run: docker compose build
